### ISSUE TITLE
Create a solution to solve the need for !important on css props

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuel-ui#128]
As we discussed previously we just implement a solution to remove the requirement of using `important` on CSS prop.

This is an issue from Stitches. https://github.com/stitchesjs/stitches/issues/1060

**Comment by pedronauck** [comment]
@luizstacio I tried during the day today how to find a solution for this inside but I couldn't. I tried many solutions but in all cases stitches suppress classes by injecting its own class and isn't possible to override without the `!important`, I'll drop this task by now and wait until some update in the library.
