### ISSUE TITLE
Make Copyable padding a bit bigger

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuel-ui#152]
### Motivation

A little bit more padding would make the Copy icon more elegant in `Copyable` component.

Here's an example, where left icon (Link) is with more padding, and right one (Copy) has default spacing from `Copyable`

https://user-images.githubusercontent.com/8636507/200466765-641f6185-da81-4b58-98bf-49408e8cdce2.mov

**Comment by josevitordaltoe** [comment]
[https://github.com/FuelLabs/fuel-ui/pull/155](url)
