### ISSUE TITLE
Allow Copyable to be used without children elements

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuel-ui#154]
### Motivation

Currently, if you want to use Copyable component, but without any text, you need to do like this:

```
<Copyable value={'ID'} children={<></>} />
```

or worse:
```
<Copyable value={'ID'}>&nbsp;</Copyable>
```
```
<Copyable value={'ID'}>{' '}</Copyable>
```

### Usage example

Copyable should allow being created with only:

```
<Copyable value={'ID'} />
```

**Comment by Aksa12** [comment]
Hey, I would like to work on this issue.
