### ISSUE TITLE
Adjust `ContentLoader` color

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuel-ui#246]
### Motivation

RN I think it's looking too dark in light theme, and too light in dark theme. we should make it more discrete

https://user-images.githubusercontent.com/8636507/235757611-11fac62c-28b1-4059-a969-2fdc32717411.mov

**Comment by matt-user** [comment]
To add on to this the generic `intentsBaseX` variables do not work when passed in.  Only the darkColors or lightColors variables work here, but it would be nice if the generic colors worked as well.
